# Generated by Django 2.0.2 on 2018-06-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
