# Generated by Django 2.0.2 on 2018-06-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
