# Generated by Django 2.0.2 on 2018-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0004_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/download/'),
        ),
    ]
